# Generated by Django 5.1.1 on 2024-11-15 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(db_column='Author_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=50, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(db_column='Book_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('language', models.CharField(blank=True, db_column='Language', max_length=50, null=True)),
                ('availability_status', models.CharField(blank=True, db_column='Availability_Status', max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('publishdate', models.DateField(blank=True, db_column='PublishDate', null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookDiscount',
            fields=[
                ('discount_id', models.IntegerField(db_column='Discount_id', primary_key=True, serialize=False)),
                ('discount', models.DecimalField(blank=True, db_column='Discount', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'book_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_column='Category_id', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='Category_Name', max_length=50)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('discount_id', models.IntegerField(blank=True, db_column='Discount_id', null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('discount_id', models.IntegerField(db_column='Discount_id', primary_key=True, serialize=False)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(db_column='Employee_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.IntegerField(db_column='Order_detail_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('price_each', models.DecimalField(blank=True, db_column='Price_each', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(db_column='Order_id', primary_key=True, serialize=False)),
                ('order_date', models.DateField(blank=True, db_column='Order_date', null=True)),
                ('shipped_date', models.DateField(blank=True, db_column='Shipped_Date', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('from_employee', models.IntegerField(blank=True, db_column='From_employee', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.IntegerField(db_column='Payment_id', primary_key=True, serialize=False)),
                ('payment_method', models.CharField(blank=True, db_column='Payment_method', max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, db_column='Payment_date', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(blank=True, db_column='Payment_status', max_length=20, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.IntegerField(db_column='Publisher_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('contact_info', models.TextField(blank=True, db_column='Contact_info', null=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.IntegerField(db_column='Review_id', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('review_date', models.DateField(blank=True, db_column='Review_date', null=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account_id', models.IntegerField(db_column='Account_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_column='User_name', max_length=50)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=50, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('registered_date', models.DateField(blank=True, db_column='Registered_date', null=True)),
                ('from_employee', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('book', models.OneToOneField(db_column='Book_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.book')),
            ],
            options={
                'db_table': 'book_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('book', models.OneToOneField(db_column='Book_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.book')),
            ],
            options={
                'db_table': 'book_category',
                'managed': False,
            },
        ),
    ]
