# Generated by Django 5.1.3 on 2024-11-30 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCoupon',
            fields=[
                ('coupon_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'book_coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.customer')),
                ('redeem_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='book',
        ),
        migrations.DeleteModel(
            name='BookDiscount',
        ),
        migrations.DeleteModel(
            name='CustomerDiscount',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
