# Generated by Django 5.1.3 on 2024-12-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.book'),
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, db_column='added_date'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(db_column='quantity', default=1),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cartitem',
        ),
    ]
